ports:
    - port: 8000
      onOpen: open-preview
tasks:
    - init: >
        npm i now -g &&
        npm install &&
        cd site && npm install;
      command: >
        cd site && npm run start;